### ISSUE TITLE
Clean up gnav

### ISSUE THREAD

**Issue by rofe** [adobe/helix-website#19]

**Comment by auniverseaway** [comment]
![Screen Shot 2021-11-01 at 8 36 19 PM](https://user-images.githubusercontent.com/1972095/139777869-fe6ecabd-e867-40d1-9d9f-68b21fe017b9.png)

This whole thing should probably change now to something like, "Develop your site" with info about the Helix bot. Works through github, pushes code, checks your speed, etc. All code focused.

**Comment by rofe** [comment]
Done.
