### ISSUE TITLE
Franklin Developer Tutorial does not define location or format of fstab.yaml

### ISSUE THREAD

**Issue by thedoc31** [adobe/helix-website#274]
In the training and sample content, multiple references to `fstab.yaml` are made, but none of them define exactly WHERE in the GDrive it should go. The sample content does not contain an example fstab.yaml for us to view/modify, so it's very confusing. It's also unclear if there's a special format for it, if we need to do anything special, put URLs in quotes, etc.

![image](https://github.com/adobe/helix-website/assets/5641900/a0c3516b-2834-4a11-b3d1-9be4384b7a4b)
![image](https://github.com/adobe/helix-website/assets/5641900/88918de4-ac53-4938-873b-94f3cc5d8499)

**Comment by trieloff** [comment]
I'm not sure how "`fstab.yaml` in your GitHub repo" could make it any clearer that the file is in your GitHub repo. By opening the file, the format will become apparent.
