### ISSUE TITLE
Docs: last three subsections are empty

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-website#338]
https://main--helix-website--adobe.hlx.page/docs/

Has the content in Markdown, but the actual content gets removed in the DOM.

**Comment by snowiewdev** [comment]
Sorry for not flagging this earlier. For the `card-list` block, we’ve combined the block with Adobe’s existing one, as the blocks in `main` and `redesign` has the same block name called `card-list`.

The original Adobe one would render `cards` based on the url provided inside the block, while redesign version takes in image and text content to render the card list.

We've combined the blocks together in `card-list` to minimize the work on content editing side, as renaming the block may need updating the docs on the existing blocks. For now in `card-list` block, it’s currently using `image-card-listing` class to identify the one in `redesign` version. By default, it will uses the original Adobe one. Please let us know if we need to create another block to avoid the confusion. Thank you.
