### ISSUE TITLE
Performance: fix CLS on main element in Doc Detail page 

### ISSUE THREAD

**Issue by snowiewdev** [adobe/helix-website#356]
Issue mentioned in this PR:
https://github.com/adobe/helix-website/issues/353#issuecomment-1649418313

Details:
- `main` element still seems to move around quite a bit:
<img width="917" alt="image" src="https://github.com/adobe/helix-website/assets/1609742/7c6e5999-225b-4bd4-9a8d-4a3a1c073d2b">.
- use`.live` URL as test URL to have a cached and more constant reference

Test Urls to be used:
Before: https://main--helix-website--adobe.hlx.page/docs/sidekick
After: https://redesign-doc-page-perf-fix--helix-website--adobe.hlx.live/docs/sidekick

**Comment by davidnuescheler** [comment]
@snowiewdev i think this was fixed https://github.com/adobe/helix-website/pull/388

**Comment by snowiewdev** [comment]
@davidnuescheler Thank you so much! The fix on #388 is looking good to me:
https://pagespeed.web.dev/analysis/https-www-hlx-live-docs-sidekick/lbesvr3spj?form_factor=desktop

Closing this issue
